#!/bin/bash

# Installs the latest version of Docker.
#
# Source: https://blog.docker.com/2015/07/new-apt-and-yum-repos/

source ${HOME}/Dropbox/development/scripts/utils.sh

msg "Removing existing Docker, if any"
sudo apt-get purge -y lxc-docker* >/dev/null 2>&1

msg "Adding the new APT Docker repositories"
wrap "sudo apt-key" adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

# NOTE: This only works for Trusty (Ubuntu 14.04 LTS)
# See the reference above for an appropriate key
sudo echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >/etc/apt/sources.list.d/docker.list
sudo apt-get update

msg "Installing Docker..."
wrap "sudo apt-get" install -y docker-engine
wrap docker version

